# config/routes.yaml
wholesale_ruleset:
  resource: |
    alias: skyboundtech.wholesale_ruleset
    section: admin
    templates: "@SkyBoundTechSyliusWholesalePlugin/CrudUi"
    redirect: update
    grid: skyboundtech.wholesale_ruleset
    vars:
        all:
            header: skyboundtech.ui.wholesale_ruleset.header
            subheader: skyboundtech.ui.wholesale_ruleset.subheader
        index:
            icon: 'file image outline'
  type: sylius.resource
  prefix: /admin

wholesale_rule:
  resource: |
    alias: skyboundtech.wholesale_rule
    section: admin
    templates: "@SyliusAdmin\\Crud"
    redirect: update
    grid: skyboundtech.wholesale_rule
    vars:
        all:
            header: skyboundtech.ui.wholesale_rule.header
            subheader: skyboundtech.ui.wholesale_rule.subheader
        index:
            icon: 'file image outline'
  type: sylius.resource
  prefix: /admin
