# config/packages/sylius_resource.yaml

#Models
sylius_channel:
  resources:
    channel:
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Channel

#New Resources
sylius_resource:
  resources:
    skyboundtech.wholesale_ruleset:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Ruleset
        form: SkyBoundTech\SyliusWholesalePlugin\Form\RulesetType
    skyboundtech.wholesale_rule:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Rule
        form: SkyBoundTech\SyliusWholesalePlugin\Form\Rule
