# config/packages/sylius_resource.yaml

#Models
sylius_channel:
  resources:
    channel:
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Channel

#New Resources
sylius_resource:
  resources:
    skyboundtech.wholesale_ruleset:
      driver: doctrine/orm
      classes:
        interface: SkyBoundTech\SyliusWholesalePlugin\Entity\RulesetInterface
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Ruleset
        repository: SkyBoundTech\SyliusWholesalePlugin\Repository\RulesetRepository
        form: SkyBoundTech\SyliusWholesalePlugin\Form\RulesetType
      translation:
        classes:
          interface: SkyBoundTech\SyliusWholesalePlugin\Entity\RulesetTranslationInterface
          model: SkyBoundTech\SyliusWholesalePlugin\Entity\RulesetTranslation
          form: SkyBoundTech\SyliusWholesalePlugin\Form\RulesetTranslationType
    skyboundtech.wholesale_rule:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Rule
        form: SkyBoundTech\SyliusWholesalePlugin\Form\RuleType
