# config/packages/sylius_resource.yaml

#Models
sylius_channel:
  resources:
    channel:
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Channel

#New Resources
sylius_resource:
  resources:
    skyboundtech.wholesale_ruleset:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesalePlugin\Entity\Ruleset
